[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
force = false
optimizer = true
auto_detect_remappings = false
optimizer_runs = 999999
solc_version = "0.8.17"
evm_version = "london"
bytecode_hash = "ipfs"
cbor_metadata = true
extra_output_files = ["metadata"]

fs_permissions = [
  { "access" = "read-write", "path" = "./script/output/"},
  { "access" = "read-write", "path" = "./deployments/" },
  { "access" = "read", "path" = "./script/c3.json"},
  { "access" = "read", "path" = "./script/input/"},
  { "access" = "read", "path" = "./broadcast/" },
  { "access" = "read", "path" = "./out/" },
  { "access" = "read", "path" = "./lib/safe-deployments/src/assets/" },
]

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"
darwinia = "https://rpc.darwinia.network"
arbitrum = "https://arb1.arbitrum.io/rpc"
polygon = "https://polygon-rpc.com"
mantle = "https://rpc.mantle.xyz"
ethereum = "https://mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"

[etherscan]
polygon = { key = "${ETHERSCAN_POLYGON_KEY}"}
arbitrum = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-goerli = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
darwinia = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://darwinia.api.subscan.io/api/scan/evm/contract/verifysource" }
pangolin = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://pangolin.api.subscan.io/api/scan/evm/contract/verifysource" }
crab = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://crab.api.subscan.io/api/scan/evm/contract/verifysource" }
